module: ml_project.pipeline
class: Pipeline
params:
  class_list:
    - module: ml_project.models.feature_selection
      class: CubeHistogram
      params:
        cut: 15
        nrBins: 45
    - module: ml_project.models.classification
      class: LDAwithYHandling


